<script lang="ts">
  import { onMount } from 'svelte';
  import { fetchBriefs, fetchBrief } from '../lib/api';
  import type { BriefMeta } from '../../shared/types';

  let weekBriefs = $state<{ date: string; html: string; type: string }[]>([]);
  let loading = $state(true);

  onMount(async () => {
    const briefs = await fetchBriefs();

    // Get this week's briefs (last 7 days)
    const now = new Date();
    const weekAgo = new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000);
    const weekStart = weekAgo.toISOString().split('T')[0]!;

    const thisWeek = briefs.filter(b => b.date >= weekStart);
    const results: { date: string; html: string; type: string }[] = [];

    for (const brief of thisWeek.slice(0, 14)) {
      const data = await fetchBrief(brief.filename);
      results.push({ date: brief.date, html: data.html, type: brief.type });
    }

    weekBriefs = results;
    loading = false;
  });

  function formatDate(dateStr: string): string {
    const d = new Date(dateStr + 'T12:00:00');
    return d.toLocaleDateString('en-US', { weekday: 'short', month: 'short', day: 'numeric' });
  }

  function typeLabel(type: string): string {
    return type.split('-').map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(' ');
  }
</script>

<div class="schedule">
  <h2>This Week</h2>

  {#if loading}
    <div class="loading">Loading schedule...</div>
  {:else if weekBriefs.length === 0}
    <div class="empty-state glass-panel">
      <p>No briefs from this week yet.</p>
      <p class="hint">Briefs are generated by scheduled cron tasks (morning brief, EOD wrap, etc.)</p>
    </div>
  {:else}
    <div class="timeline">
      {#each weekBriefs as entry}
        <div class="timeline-entry glass-panel">
          <div class="entry-header">
            <span class="entry-date">{formatDate(entry.date)}</span>
            <span class="entry-type type-{entry.type}">{typeLabel(entry.type)}</span>
          </div>
          <div class="entry-content">
            {@html entry.html}
          </div>
        </div>
      {/each}
    </div>
  {/if}
</div>

<style>
  .schedule {
    max-width: 900px;
  }

  h2 {
    margin: 0 0 1.5rem 0;
    font-size: 1.1rem;
    color: #e6edf3;
  }

  .glass-panel {
    background: rgba(255, 255, 255, 0.04);
    backdrop-filter: blur(16px);
    border: 1px solid rgba(255, 255, 255, 0.08);
    border-radius: 12px;
    padding: 1.5rem;
  }

  .timeline {
    display: flex;
    flex-direction: column;
    gap: 1rem;
  }

  .timeline-entry {
    position: relative;
  }

  .entry-header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    margin-bottom: 1rem;
    padding-bottom: 0.75rem;
    border-bottom: 1px solid rgba(255, 255, 255, 0.06);
  }

  .entry-date {
    font-size: 0.9rem;
    font-weight: 600;
    color: #e6edf3;
  }

  .entry-type {
    font-size: 0.7rem;
    font-weight: 500;
    padding: 0.15rem 0.5rem;
    border-radius: 4px;
    background: rgba(255, 255, 255, 0.05);
  }

  .type-morning-brief { color: #58a6ff; }
  .type-eod-wrap { color: #d29922; }
  .type-weekly-plan { color: #3fb950; }

  .entry-content {
    color: #c9d1d9;
    line-height: 1.7;
    font-size: 0.85rem;
  }

  .entry-content :global(h1),
  .entry-content :global(h2),
  .entry-content :global(h3) {
    color: #e6edf3;
    margin-top: 1rem;
    margin-bottom: 0.5rem;
    font-size: 0.95rem;
  }

  .entry-content :global(ul) {
    padding-left: 1.25rem;
  }

  .entry-content :global(strong) {
    color: #58a6ff;
  }

  .empty-state {
    text-align: center;
    padding: 3rem;
    color: rgba(255, 255, 255, 0.4);
  }

  .hint {
    font-size: 0.8rem;
    color: rgba(255, 255, 255, 0.25);
    margin-top: 0.5rem;
  }

  .loading {
    text-align: center;
    padding: 3rem;
    color: rgba(255, 255, 255, 0.3);
  }
</style>
